spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/webbanhang2?useSSL=false&serverTimezone=UTC"
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
jwt:
  signerKey: "9G81oVFm6g6V5b/lBG/NERLki1cV0EHmboDnCAaQMfttN/9rcWCORgXsGXc8Q9v2"